version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend/new_new/backend
    container_name: fastapi_app
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/app_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pg_data:
